import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <h1 className="m-2 p-4 text-center bg-emerald-500">
            This is auth component
          </h1>
          {children}
        </main>
      </body>
    </html>
  );
}
